apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Release.Name }}-{{ .Chart.Name }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  ports:
    - name: "80"
      port: 80
    - name: "443"
      port: 443
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
