config:
  selfUrl: https://eshop-st-public-web
  gatewayUrl: https://eshop-st-gateway-web-public
  authServer:
    authority: http://eshop-st-authserver
    requireHttpsMetadata: "false"
    isOnProd: false
    metaAddress: #
  dotnetEnv: Staging
  redisHost: eshop-st-redis
  rabbitmqHost: eshop-st-rabbitmq
  elasticsearchHost: eshop-st-elasticsearch
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  

ingress:
  host: eshop-st-public-web
  tlsSecret: eshop-wildcard-tls

image:
  repository: eshoponabp/app-publicweb
  tag: latest
  pullPolicy: IfNotPresent

env: {}
