config:
  selfUrl: # https://eshop-st-basket
  corsOrigins: # https://eshop-st-gateway-web,https://eshop-st-gateway-public-web,https://eshop-st-public
  connectionStrings:
    administrationService: #
  authServer:
    authority: http://eshop-st-authserver
    requireHttpsMetadata: "false"
    swaggerClientId: "WebGateway_Swagger"
    swaggerClientSecret: "1q2w3e*"
  dotnetEnv: Staging
  redisHost: eshop-st-redis
  rabbitmqHost: eshop-st-rabbitmq
  elasticsearchHost: eshop-st-elasticsearch
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  remoteServices:
    catalogBaseUrl: #
    catalogGrpcUrl: #

ingress:
  host: eshop-st-basket
  tlsSecret: eshop-wildcard-tls

image:
  repository: eshoponabp/service-basket
  tag: latest
  pullPolicy: IfNotPresent

env: {}
    